"""creating phase 6 models

Revision ID: e06482a405fb
Revises: db1cc3db368e
Create Date: 2026-06-12 13:32:12.203914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e06482a405fb'
down_revision: Union[str, Sequence[str], None] = 'db1cc3db368e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    op.drop_index(op.f('code'), table_name='organization')
    op.drop_index(op.f('contact_email'), table_name='organization')
    op.drop_index(op.f('contact_phone'), table_name='organization')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_forecast_revisions_created_at'), table_name='forecast_revisions')
    op.drop_index(op.f('ix_forecast_revisions_forecast_date'), table_name='forecast_revisions')
    op.drop_index(op.f('ix_forecast_revisions_id'), table_name='forecast_revisions')
    op.drop_table('forecast_revisions')
    op.drop_index(op.f('ix_alert_settings_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_forecast_history_id'), table_name='forecast_history')
    op.drop_table('forecast_history')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_project_datasets_id'), table_name='project_datasets')
    op.drop_table('project_datasets')
    op.drop_index(op.f('ix_dataset_modifications_id'), table_name='dataset_modifications')
    op.drop_index(op.f('ix_dataset_modifications_modified_at'), table_name='dataset_modifications')
    op.drop_table('dataset_modifications')
    op.drop_table('forecast_schedules')
    op.drop_index(op.f('ix_report_shares_id'), table_name='report_shares')
    op.drop_table('report_shares')
    op.drop_table('inventory')
    op.drop_index(op.f('idx_timestamp'), table_name='api_logs')
    op.drop_index(op.f('idx_username'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index(op.f('ix_forecast_projects_id'), table_name='forecast_projects')
    op.drop_table('forecast_projects')
    op.drop_index(op.f('ix_project_activity_id'), table_name='project_activity')
    op.drop_table('project_activity')
    op.drop_table('alerts')
    op.drop_index(op.f('idx_category'), table_name='sales')
    op.drop_index(op.f('idx_product_name'), table_name='sales')
    op.drop_index(op.f('idx_region'), table_name='sales')
    op.drop_index(op.f('idx_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_category'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_region'), table_name='sales')
    op.drop_index(op.f('ix_sales_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_dataset_versions_dataset_name'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_uploaded_at'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_project_forecasts_id'), table_name='project_forecasts')
    op.drop_table('project_forecasts')
    op.drop_index(op.f('idx_forecast_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_report_schedules_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_forecast_activity_timeline_id'), table_name='forecast_activity_timeline')
    op.drop_index(op.f('ix_forecast_activity_timeline_timestamp'), table_name='forecast_activity_timeline')
    op.drop_table('forecast_activity_timeline')
    op.drop_index(op.f('ix_forecast_comments_id'), table_name='forecast_comments')
    op.drop_table('forecast_comments')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forecast_accuracy_id'), table_name='forecast_accuracy')
    op.drop_table('forecast_accuracy')
    op.drop_index(op.f('ix_inventory_integrations_id'), table_name='inventory_integrations')
    op.drop_table('inventory_integrations')
    op.drop_index(op.f('ix_collaboration_invitations_id'), table_name='collaboration_invitations')
    op.drop_table('collaboration_invitations')
    op.drop_index(op.f('ix_project_reports_id'), table_name='project_reports')
    op.drop_table('project_reports')
    op.drop_index(op.f('ix_dataset_upload_history_id'), table_name='dataset_upload_history')
    op.drop_index(op.f('ix_dataset_upload_history_uploaded_at'), table_name='dataset_upload_history')
    op.drop_table('dataset_upload_history')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('user_id'), table_name='dashboard_preferences')
    op.drop_table('dashboard_preferences')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_project_discussions_id'), table_name='project_discussions')
    op.drop_table('project_discussions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_discussions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['project_discussions.id'], name=op.f('project_discussions_ibfk_3')),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_discussions_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_discussions_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_discussions_id'), 'project_discussions', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('generated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('reports_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('dashboard_preferences',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_kpi', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_revenue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_profit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_growth', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_cost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_ai_insights', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('dashboard_preferences_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dashboard_preferences_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'dashboard_preferences', ['user_id'], unique=True)
    op.create_table('project_members',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('joined_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_members_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_members_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('dataset_upload_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uploaded_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upload_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('rows_uploaded', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_cleaned', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duplicates_removed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cleaning_report', mysql.TEXT(), nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('dataset_upload_history_ibfk_1')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('dataset_upload_history_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_dataset_upload_history_uploaded_at'), 'dataset_upload_history', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_dataset_upload_history_id'), 'dataset_upload_history', ['id'], unique=False)
    op.create_table('project_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('added_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_reports_ibfk_1')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('project_reports_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_reports_id'), 'project_reports', ['id'], unique=False)
    op.create_table('collaboration_invitations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('invited_at', mysql.DATETIME(), nullable=True),
    sa.Column('responded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('collaboration_invitations_ibfk_2')),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], name=op.f('collaboration_invitations_ibfk_3')),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('collaboration_invitations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_collaboration_invitations_id'), 'collaboration_invitations', ['id'], unique=False)
    op.create_table('inventory_integrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('system_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('api_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('api_key', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_sync', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_inventory_integrations_id'), 'inventory_integrations', ['id'], unique=False)
    op.create_table('forecast_accuracy',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evaluation_date', sa.DATE(), nullable=True),
    sa.Column('actual_demand', mysql.FLOAT(), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('accuracy_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('model_type', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('forecast_accuracy_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_accuracy_id'), 'forecast_accuracy', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reset_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token_expiry', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('users_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('forecast_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast_results.id'], name=op.f('forecast_comments_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('forecast_comments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_comments_id'), 'forecast_comments', ['id'], unique=False)
    op.create_table('forecast_activity_timeline',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('meta_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast_results.id'], name=op.f('forecast_activity_timeline_ibfk_1')),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('forecast_activity_timeline_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('forecast_activity_timeline_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_activity_timeline_timestamp'), 'forecast_activity_timeline', ['timestamp'], unique=False)
    op.create_index(op.f('ix_forecast_activity_timeline_id'), 'forecast_activity_timeline', ['id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('frequency', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('day_of_week', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('day_of_month', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('next_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('report_schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_schedules_id'), 'report_schedules', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast_date', sa.DATE(), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('prophet_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('lr_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('ma_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('sales_trend', mysql.FLOAT(), nullable=True),
    sa.Column('weekly_pattern', mysql.FLOAT(), nullable=True),
    sa.Column('yearly_pattern', mysql.FLOAT(), nullable=True),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=True),
    sa.Column('approval_status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('forecast_results_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_results_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_index(op.f('idx_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_table('project_forecasts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forecast_result_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_result_id'], ['forecast_results.id'], name=op.f('project_forecasts_ibfk_2')),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_forecasts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_forecasts_id'), 'project_forecasts', ['id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('total_rows', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_columns', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size_kb', mysql.FLOAT(), nullable=True),
    sa.Column('columns_snapshot', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('archived_at', mysql.DATETIME(), nullable=True),
    sa.Column('uploaded_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('dataset_versions_ibfk_2')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('dataset_versions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_dataset_versions_uploaded_at'), 'dataset_versions', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_dataset_versions_id'), 'dataset_versions', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_dataset_name'), 'dataset_versions', ['dataset_name'], unique=False)
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sales_date', sa.DATE(), nullable=True),
    sa.Column('quantity_sold', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue', mysql.FLOAT(), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('stock_available', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('customer_age', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('customer_gender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('customer_segment', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('sales_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sales_sales_date'), 'sales', ['sales_date'], unique=False)
    op.create_index(op.f('ix_sales_region'), 'sales', ['region'], unique=False)
    op.create_index(op.f('ix_sales_product_name'), 'sales', ['product_name'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_category'), 'sales', ['category'], unique=False)
    op.create_index(op.f('idx_sales_date'), 'sales', ['sales_date'], unique=False)
    op.create_index(op.f('idx_region'), 'sales', ['region'], unique=False)
    op.create_index(op.f('idx_product_name'), 'sales', ['product_name'], unique=False)
    op.create_index(op.f('idx_category'), 'sales', ['category'], unique=False)
    op.create_table('alerts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_activity',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_activity_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_activity_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_activity_id'), 'project_activity', ['id'], unique=False)
    op.create_table('forecast_projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('forecast_projects_ibfk_1')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('forecast_projects_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_projects_id'), 'forecast_projects', ['id'], unique=False)
    op.create_table('api_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_index(op.f('idx_username'), 'api_logs', ['username'], unique=False)
    op.create_index(op.f('idx_timestamp'), 'api_logs', ['timestamp'], unique=False)
    op.create_table('inventory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_system', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('synced_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_shares',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_to', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('shared_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_shares_ibfk_1')),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], name=op.f('report_shares_ibfk_2')),
    sa.ForeignKeyConstraint(['shared_to'], ['users.id'], name=op.f('report_shares_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_shares_id'), 'report_shares', ['id'], unique=False)
    op.create_table('forecast_schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('interval_value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('forecast_schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dataset_modifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modification_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('rows_affected', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_value', mysql.TEXT(), nullable=True),
    sa.Column('new_value', mysql.TEXT(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('dataset_modifications_ibfk_1')),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=op.f('dataset_modifications_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_dataset_modifications_modified_at'), 'dataset_modifications', ['modified_at'], unique=False)
    op.create_index(op.f('ix_dataset_modifications_id'), 'dataset_modifications', ['id'], unique=False)
    op.create_table('project_datasets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sales_reference_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('project_datasets_ibfk_1')),
    sa.ForeignKeyConstraint(['sales_reference_id'], ['sales.id'], name=op.f('project_datasets_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_datasets_id'), 'project_datasets', ['id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insight_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('ai_insights_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('forecast_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('model_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_history_id'), 'forecast_history', ['id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_trained_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_sales_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_table('alert_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('high_demand_threshold', mysql.FLOAT(), nullable=True),
    sa.Column('low_stock_threshold', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('forecast_failure_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('report_completion_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_alert_settings_id'), 'alert_settings', ['id'], unique=False)
    op.create_table('forecast_revisions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('revision_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forecast_date', sa.DATE(), nullable=False),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=False),
    sa.Column('prophet_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('lr_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('ma_prediction', mysql.FLOAT(), nullable=True),
    sa.Column('sales_trend', mysql.FLOAT(), nullable=True),
    sa.Column('weekly_pattern', mysql.FLOAT(), nullable=True),
    sa.Column('yearly_pattern', mysql.FLOAT(), nullable=True),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=True),
    sa.Column('model_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('change_summary', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('forecast_revisions_ibfk_1')),
    sa.ForeignKeyConstraint(['project_id'], ['forecast_projects.id'], name=op.f('forecast_revisions_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_revisions_id'), 'forecast_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_revisions_forecast_date'), 'forecast_revisions', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_revisions_created_at'), 'forecast_revisions', ['created_at'], unique=False)
    op.create_table('organization',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('industry', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=2550), nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_index(op.f('contact_phone'), 'organization', ['contact_phone'], unique=True)
    op.create_index(op.f('contact_email'), 'organization', ['contact_email'], unique=True)
    op.create_index(op.f('code'), 'organization', ['code'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scenario_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sales_growth_factor', mysql.FLOAT(), nullable=True),
    sa.Column('seasonality_factor', mysql.FLOAT(), nullable=True),
    sa.Column('demand_factor', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('scenarios_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
