from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import Optional
from datetime import datetime, timedelta
import math
import os

import pandas as pd
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4

from app.db.database import get_db
from app.models.user import User
from app.models.sales import Sales
from app.models.forecast_results import ForecastResult
from app.models.forecast_accuracy import ForecastAccuracy
from app.models.model_metadata import ModelMetadata
from app.models.reports import Report
from app.models.report_schedule import ReportSchedule
from app.core.security import get_current_user, verify_role
from app.utils.response import success_response
from app.utils.logger import log_api_activity
from app.schemas.executive_reports import ScheduleCreate, ScheduleUpdate

router = APIRouter(prefix="/executive-reports", tags=["Executive Reports"])

REPORTS_DIR = "reports/executive_reports"

# ── Helper: Save report record to DB ──
def save_report_record(db, filename, file_path, file_type, username):
    report = Report(
        filename=filename,
        file_path=file_path,
        file_type=file_type,
        generated_by=username
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


# ── Helper: MAE ──
def compute_mae(actual, predicted):
    if not actual:
        return None
    return round(
        sum(abs(a - p) for a, p in zip(actual, predicted)) / len(actual), 2
    )


# ──────────────────────────────────────────
# 8.1 — Executive Summary Report (PDF)
# ──────────────────────────────────────────

@router.get("/executive-summary")
def executive_summary_report(
    db: Session = Depends(get_db),
    user = Depends(verify_role("all"))
):
    """
    Generates a management-ready executive summary PDF covering:
    total revenue, top products, forecast accuracy, demand outlook.
    """

    # Gather data
    total_revenue = db.query(func.sum(Sales.revenue)).scalar() or 0
    total_qty = db.query(func.sum(Sales.quantity_sold)).scalar() or 0
    total_records = db.query(Sales).count()

    top_products = db.query(
        Sales.product_name,
        func.sum(Sales.quantity_sold).label("qty")
    ).group_by(Sales.product_name).order_by(
        func.sum(Sales.quantity_sold).desc()
    ).limit(5).all()

    accuracy_rows = db.query(ForecastAccuracy).all()
    avg_accuracy = round(
        sum(r.accuracy_percentage for r in accuracy_rows) / len(accuracy_rows), 2
    ) if accuracy_rows else 0

    forecasts = db.query(ForecastResult).order_by(
        ForecastResult.forecast_date.asc()
    ).limit(10).all()

    metadata = db.query(ModelMetadata).first()

    # Build PDF
    filename = f"executive_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Executive Summary Report", styles["Title"]))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')} | Generated By: {current_user.username}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 20))

    # KPI Section
    elements.append(Paragraph("Key Performance Indicators", styles["Heading2"]))
    kpi_data = [
        ["Metric", "Value"],
        ["Total Revenue", f"₹{round(total_revenue, 2):,}"],
        ["Total Quantity Sold", f"{int(total_qty):,}"],
        ["Total Sales Records", f"{total_records:,}"],
        ["Forecast Accuracy", f"{avg_accuracy}%"],
        ["Last Model Trained", str(metadata.last_trained_at)[:19] if metadata else "N/A"]
    ]
    kpi_table = Table(kpi_data, colWidths=[250, 200])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#065f46")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8)
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 20))

    # Top Products
    elements.append(Paragraph("Top 5 Products by Demand", styles["Heading2"]))
    prod_data = [["Product", "Quantity Sold"]] + [
        [p.product_name, f"{int(p.qty):,}"] for p in top_products
    ]
    prod_table = Table(prod_data, colWidths=[300, 150])
    prod_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#065f46")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8)
    ]))
    elements.append(prod_table)
    elements.append(Spacer(1, 20))

    # Demand Outlook
    elements.append(Paragraph("Demand Outlook (Next 10 Periods)", styles["Heading2"]))
    forecast_data = [["Forecast Date", "Predicted Demand", "Confidence Score"]] + [
        [str(f.forecast_date), round(f.predicted_demand, 2), f"{round(f.confidence_score, 1)}%"]
        for f in forecasts
    ]
    forecast_table = Table(forecast_data, colWidths=[170, 170, 120])
    forecast_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#065f46")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8)
    ]))
    elements.append(forecast_table)

    doc.build(elements)
    save_report_record(db, filename, file_path, "pdf", current_user.username)

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/pdf"
    )


# ──────────────────────────────────────────
# 8.2 — Monthly Business Forecast Report (Excel)
# ──────────────────────────────────────────

@router.get("/monthly-forecast-report")
def monthly_forecast_report(
    year: Optional[int] = Query(None, description="Filter by year e.g. 2024"),
    db: Session = Depends(get_db),
    user = Depends(verify_role("all"))
):
    """
    Generates a monthly aggregated forecast + sales Excel report.
    Groups actual sales and predicted demand by month.
    """

    sales_query = db.query(
        func.date_format(Sales.sales_date, "%Y-%m").label("month"),
        func.sum(Sales.revenue).label("total_revenue"),
        func.sum(Sales.quantity_sold).label("total_qty")
    ).group_by("month")

    if year:
        sales_query = sales_query.filter(
            func.year(Sales.sales_date) == year
        )

    monthly_sales = sales_query.order_by("month").all()

    forecast_rows = db.query(ForecastResult).order_by(
        ForecastResult.forecast_date.asc()
    ).all()

    # Group forecast by month
    forecast_monthly = {}
    for f in forecast_rows:
        key = str(f.forecast_date)[:7]
        if key not in forecast_monthly:
            forecast_monthly[key] = []
        forecast_monthly[key].append(f.predicted_demand)

    # Build Excel
    data = []
    for row in monthly_sales:
        avg_forecast = None
        if row.month in forecast_monthly:
            vals = forecast_monthly[row.month]
            avg_forecast = round(sum(vals) / len(vals), 2)
        data.append({
            "Month": row.month,
            "Actual Revenue (₹)": round(float(row.total_revenue), 2),
            "Actual Quantity Sold": int(row.total_qty),
            "Avg Forecasted Demand": avg_forecast or "N/A"
        })

    df = pd.DataFrame(data)
    filename = f"monthly_forecast_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    file_path = os.path.join(REPORTS_DIR, filename)

    with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Monthly Forecast")
        worksheet = writer.sheets["Monthly Forecast"]
        for col in worksheet.columns:
            worksheet.column_dimensions[col[0].column_letter].width = 22

    save_report_record(db, filename, file_path, "excel", current_user.username)

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )


# ──────────────────────────────────────────
# 8.3 — Revenue and Demand Outlook Report (PDF)
# ──────────────────────────────────────────

@router.get("/revenue-outlook-report")
def revenue_outlook_report(
    db: Session = Depends(get_db),
    user = Depends(verify_role("all"))
):
    """
    Generates a forward-looking revenue and demand outlook PDF.
    Combines historical revenue trends with future forecast projections.
    """

    # Historical monthly revenue
    monthly_revenue = db.query(
        func.date_format(Sales.sales_date, "%Y-%m").label("month"),
        func.sum(Sales.revenue).label("revenue")
    ).group_by("month").order_by("month").all()

    # Future forecast projections
    future_forecasts = db.query(ForecastResult).order_by(
        ForecastResult.forecast_date.asc()
    ).limit(10).all()

    # Build PDF
    filename = f"revenue_outlook_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Revenue & Demand Outlook Report", styles["Title"]))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y')} | By: {current_user.username}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 20))

    # Historical Revenue
    elements.append(Paragraph("Historical Monthly Revenue", styles["Heading2"]))
    rev_data = [["Month", "Total Revenue (₹)"]] + [
        [row.month, f"₹{round(float(row.revenue), 2):,}"]
        for row in monthly_revenue
    ]
    rev_table = Table(rev_data, colWidths=[250, 200])
    rev_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eff6ff")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8)
    ]))
    elements.append(rev_table)
    elements.append(Spacer(1, 20))

    # Demand Outlook
    elements.append(Paragraph("Future Demand Projections", styles["Heading2"]))
    outlook_data = [["Date", "Predicted Demand", "Est. Revenue (₹)", "Confidence"]] + [
        [
            str(f.forecast_date),
            round(f.predicted_demand, 2),
            f"₹{round(f.predicted_demand * 100, 2):,}",
            f"{round(f.confidence_score, 1)}%"
        ]
        for f in future_forecasts
    ]
    outlook_table = Table(outlook_data, colWidths=[130, 130, 130, 80])
    outlook_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eff6ff")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8)
    ]))
    elements.append(outlook_table)

    doc.build(elements)
    save_report_record(db, filename, file_path, "pdf", current_user.username)

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/pdf"
    )


# ──────────────────────────────────────────
# 8.4 — Management Analytics Summary (Excel)
# ──────────────────────────────────────────

@router.get("/management-summary-report")
def management_summary_report(
    db: Session = Depends(get_db),
    user = Depends(verify_role("all"))
):
    """
    Generates a multi-sheet management analytics Excel report covering:
    KPIs, top products, regional performance, forecast accuracy, model metrics.
    """

    # KPI Data
    total_revenue = db.query(func.sum(Sales.revenue)).scalar() or 0
    total_qty = db.query(func.sum(Sales.quantity_sold)).scalar() or 0
    total_records = db.query(Sales).count()
    accuracy_rows = db.query(ForecastAccuracy).all()
    avg_accuracy = round(
        sum(r.accuracy_percentage for r in accuracy_rows) / len(accuracy_rows), 2
    ) if accuracy_rows else 0
    metadata = db.query(ModelMetadata).first()

    kpi_df = pd.DataFrame([{
        "Metric": "Total Revenue (₹)",
        "Value": round(total_revenue, 2)
    }, {
        "Metric": "Total Quantity Sold",
        "Value": int(total_qty)
    }, {
        "Metric": "Total Sales Records",
        "Value": total_records
    }, {
        "Metric": "Avg Forecast Accuracy (%)",
        "Value": avg_accuracy
    }, {
        "Metric": "Last Model Trained",
        "Value": str(metadata.last_trained_at)[:19] if metadata else "N/A"
    }])

    # Top Products
    top_products = db.query(
        Sales.product_name,
        func.sum(Sales.quantity_sold).label("qty"),
        func.sum(Sales.revenue).label("revenue")
    ).group_by(Sales.product_name).order_by(
        func.sum(Sales.quantity_sold).desc()
    ).limit(10).all()

    products_df = pd.DataFrame([{
        "Product": p.product_name,
        "Quantity Sold": int(p.qty),
        "Revenue (₹)": round(float(p.revenue), 2)
    } for p in top_products])

    # Regional Performance
    regional = db.query(
        Sales.region,
        func.sum(Sales.quantity_sold).label("qty"),
        func.sum(Sales.revenue).label("revenue")
    ).group_by(Sales.region).all()

    regional_df = pd.DataFrame([{
        "Region": r.region,
        "Quantity Sold": int(r.qty),
        "Revenue (₹)": round(float(r.revenue), 2)
    } for r in regional])

    # Forecast Accuracy
    accuracy_df = pd.DataFrame([{
        "Date": str(r.evaluation_date),
        "Actual Demand": r.actual_demand,
        "Predicted Demand": r.predicted_demand,
        "Accuracy (%)": r.accuracy_percentage,
        "Model": r.model_type
    } for r in accuracy_rows])

    # Write multi-sheet Excel
    filename = f"management_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    file_path = os.path.join(REPORTS_DIR, filename)

    with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
        kpi_df.to_excel(writer, index=False, sheet_name="KPI Summary")
        products_df.to_excel(writer, index=False, sheet_name="Top Products")
        regional_df.to_excel(writer, index=False, sheet_name="Regional Performance")
        accuracy_df.to_excel(writer, index=False, sheet_name="Forecast Accuracy")

        for sheet in writer.sheets.values():
            for col in sheet.columns:
                sheet.column_dimensions[col[0].column_letter].width = 22

    save_report_record(db, filename, file_path, "excel", current_user.username)

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )


# ──────────────────────────────────────────
# 8.5 — Report Schedule Configuration
# ──────────────────────────────────────────

VALID_REPORT_TYPES = [
    "executive_summary",
    "monthly_forecast",
    "revenue_outlook",
    "management_summary"
]

VALID_FREQUENCIES = ["daily", "weekly", "monthly"]

@router.post("/schedules/create")
def create_schedule(
    payload: ScheduleCreate,
    db: Session = Depends(get_db),
    user = Depends(verify_role("manager"))
):
    if payload.report_type not in VALID_REPORT_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid report_type. Choose from: {VALID_REPORT_TYPES}"
        )

    if payload.frequency not in VALID_FREQUENCIES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid frequency. Choose from: {VALID_FREQUENCIES}"
        )

    # Compute next_run_at
    now = datetime.utcnow()
    if payload.frequency == "daily":
        next_run = now + timedelta(days=1)
    elif payload.frequency == "weekly":
        next_run = now + timedelta(weeks=1)
    else:
        next_run = now + timedelta(days=30)

    schedule = ReportSchedule(
        report_type=payload.report_type,
        frequency=payload.frequency,
        day_of_week=payload.day_of_week,
        day_of_month=payload.day_of_month,
        created_by=current_user.id,
        next_run_at=next_run
    )

    db.add(schedule)
    db.commit()
    db.refresh(schedule)

    return success_response(
        message="Report schedule created successfully!",
        data={
            "id": schedule.id,
            "report_type": schedule.report_type,
            "frequency": schedule.frequency,
            "is_active": schedule.is_active,
            "next_run_at": schedule.next_run_at
        }
    )


@router.get("/schedules")
def list_schedules(
    db: Session = Depends(get_db),
    user = Depends(verify_role("all"))
):
    schedules = db.query(ReportSchedule).order_by(
        ReportSchedule.created_at.desc()
    ).all()

    return success_response(
        message="Report schedules fetched successfully!",
        data=[{
            "id": s.id,
            "report_type": s.report_type,
            "frequency": s.frequency,
            "day_of_week": s.day_of_week,
            "day_of_month": s.day_of_month,
            "is_active": s.is_active,
            "last_run_at": s.last_run_at,
            "next_run_at": s.next_run_at,
            "created_at": s.created_at
        } for s in schedules]
    )


@router.put("/schedules/{schedule_id}")
def update_schedule(
    schedule_id: int,
    payload: ScheduleUpdate,
    db: Session = Depends(get_db),
    user = Depends(verify_role("manager"))
):
    schedule = db.query(ReportSchedule).filter(
        ReportSchedule.id == schedule_id
    ).first()

    if not schedule:
        raise HTTPException(status_code=404, detail="Schedule not found")

    if schedule.created_by != current_user.id:
        raise HTTPException(status_code=403, detail="Only the creator can update this schedule")

    if payload.frequency:
        schedule.frequency = payload.frequency
    if payload.day_of_week:
        schedule.day_of_week = payload.day_of_week
    if payload.day_of_month:
        schedule.day_of_month = payload.day_of_month
    if payload.is_active is not None:
        schedule.is_active = payload.is_active

    db.commit()
    db.refresh(schedule)

    return success_response(
        message="Schedule updated successfully!",
        data={
            "id": schedule.id,
            "report_type": schedule.report_type,
            "frequency": schedule.frequency,
            "is_active": schedule.is_active
        }
    )


@router.delete("/schedules/{schedule_id}")
def delete_schedule(
    schedule_id: int,
    db: Session = Depends(get_db),
    user = Depends(verify_role("admins"))
):
    schedule = db.query(ReportSchedule).filter(
        ReportSchedule.id == schedule_id
    ).first()

    if not schedule:
        raise HTTPException(status_code=404, detail="Schedule not found")

    if schedule.created_by != current_user.id:
        raise HTTPException(status_code=403, detail="Only the creator can delete this schedule")

    db.delete(schedule)
    db.commit()

    return success_response(message="Schedule deleted successfully!")